# Generated by Django 2.1.8 on 2019-06-03 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=250, verbose_name='addressLine1')),
                ('addressLine2', models.CharField(blank=True, max_length=250, null=True, verbose_name='addressLine2')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('postalCode', models.CharField(max_length=10, verbose_name='postalCode')),
                ('country', models.CharField(default='United States', max_length=250, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='totalPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionName', models.CharField(max_length=250, unique=True, verbose_name='collectionName')),
                ('collectionDescription', models.CharField(max_length=500, verbose_name='collectionDescription')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='isAdmin')),
                ('isVendor', models.BooleanField(default=False, verbose_name='isVendor')),
                ('isFarmer', models.BooleanField(default=False, verbose_name='isFarmer')),
                ('customerAddress', models.ManyToManyField(to='main.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True, verbose_name='orderDate')),
                ('status', models.TextField(default='Order Received', max_length=250, verbose_name='status')),
                ('cartID', models.ForeignKey(on_delete=main.models.Cart, to='main.Cart')),
                ('customer', models.ForeignKey(on_delete=main.models.Customer, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=250, unique=True, verbose_name='productName')),
                ('productDescription', models.TextField(verbose_name='productDescription')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='productPrice')),
                ('productCart', models.ManyToManyField(to='main.Cart')),
                ('productCollection', models.ForeignKey(on_delete=main.models.Collection, to='main.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/productImages/', verbose_name='img')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=main.models.Product, to='main.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=main.models.Customer, to='main.Customer'),
        ),
    ]
